## Probability

### 1. Basic Probability Theory

In [3]:
# pip install torch torchvision
# pip install -U d2l

In [3]:
%matplotlib inline
import torch
from torch.distributions import multinomial
from d2l import torch as d2l

- dice! : {1,…,6} are equally likely to occur -> probability 1/6
- estimate of the probability of a given event  

-> The law of large numbers tell us that as the number of tosses grows this estimate will draw closer and closer to the true underlying probability.

-> loop? (x) multiple samples at once (o)

In [4]:
fair_probs = torch.ones([6]) / 6
multinomial.Multinomial(1, fair_probs).sample()

tensor([0., 1., 0., 0., 0., 0.])

In [5]:
multinomial.Multinomial(10, fair_probs).sample()

tensor([4., 1., 0., 2., 2., 1.])

- after each of the 1000 rolls, how many times each number was rolled.   

-> we calculate the relative frequency as the estimate of the true probability.

In [6]:
counts = multinomial.Multinomial(1000, fair_probs).sample()
counts / 1000  # Relative frequency as the estimate

tensor([0.1510, 0.1710, 0.1490, 0.1800, 0.1800, 0.1690])

- we know that each outcome has true probability 1/6 , roughly 0.167 -> good results!

- visualize how these probabilities converge over time towards the true probability

In [ ]:
counts = multinomial.Multinomial(10, fair_probs).sample((500,))
cum_counts = counts.cumsum(dim=0)
estimates = cum_counts / cum_counts.sum(dim=1, keepdims=True)

d2l.set_figsize((6, 4.5))
for i in range(6):
    d2l.plt.plot(estimates[:, i].numpy(), label=("P(die=" + str(i + 1) + ")"))
d2l.plt.axhline(y=0.167, color='black', linestyle='dashed')
d2l.plt.gca().set_xlabel('Groups of experiments')
d2l.plt.gca().set_ylabel('Estimated probability')
d2l.plt.legend();