## Automatic Differentiation

### 1. Scalar Variables

- differentiating the function  y = 2x.Tx  with respect to the column vector x

In [9]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

- calculating the gradient of y with respect to x  

-> we do not allocate new memory every time we take a derivative with respect to a parameter

- Since x is a vector of length 4, an inner product of x and x is performed -> scalar output -> assign y

In [10]:
x.requires_grad_(True)  # Same as `x = torch.arange(4.0, requires_grad=True)`
x.grad  # The default value is None

In [11]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

- automatically calculating the gradient of y with respect to each component of x  

-> calling the function for backpropagation and printing the gradient.

In [12]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

- The gradient of the function y = 2x.Tx with respect toxshould be 4x -> check!

In [13]:
x.grad == 4 * x

tensor([True, True, True, True])

### 2. Non-Scalar Variable

- For higher-dimensional y and x, the differentiation result could be a high-order tensor
- calculate the differentiation matrix but rather the sum of the partial derivatives computed individually for each example in the batch.

In [14]:
x.grad.zero_()
y = x * x

y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [15]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [16]:
a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

- it is piecewise linear in its input a. In other words, for any a there exists some constant scalar k such that f(a) = k * a, 
where the value of k depends on the input a. Consequently d / a allows us to verify that the gradient is correct.

In [17]:
a.grad == d / a

tensor(True)